<a href="https://colab.research.google.com/github/peisbelb/module1-codexes-claims-analysis/blob/main/analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [67]:
import pandas as pd

In [68]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.1.4)
Requirement already satisfied: numpy<2,>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [71]:
df = pd.read_csv('https://data.cms.gov/sites/default/files/2023-04/67157de9-d962-4af0-bf0e-3578b3afec58/inpatient.csv')

In [73]:
df

      BENE_ID|CLM_ID|NCH_NEAR_LINE_REC_IDENT_CD|NCH_CLM_TYPE_CD|CLM_FROM_DT|CLM_THRU_DT|NCH_WKLY_PROC_DT|FI_CLM_PROC_DT|CLAIM_QUERY_CODE|PRVDR_NUM|CLM_FAC_TYPE_CD|CLM_SRVC_CLSFCTN_TYPE_CD|CLM_FREQ_CD|FI_NUM|CLM_MDCR_NON_PMT_RSN_CD|CLM_PMT_AMT|NCH_PRMRY_PYR_CLM_PD_AMT|NCH_PRMRY_PYR_CD|FI_CLM_ACTN_CD|PRVDR_STATE_CD|ORG_NPI_NUM|AT_PHYSN_UPIN|AT_PHYSN_NPI|OP_PHYSN_UPIN|OP_PHYSN_NPI|OT_PHYSN_UPIN|OT_PHYSN_NPI|CLM_MCO_PD_SW|PTNT_DSCHRG_STUS_CD|CLM_PPS_IND_CD|CLM_TOT_CHRG_AMT|CLM_ADMSN_DT|CLM_IP_ADMSN_TYPE_CD|CLM_SRC_IP_ADMSN_CD|NCH_PTNT_STATUS_IND_CD|CLM_PASS_THRU_PER_DIEM_AMT|NCH_BENE_IP_DDCTBL_AMT|NCH_BENE_PTA_COINSRNC_LBLTY_AM|NCH_BENE_BLOOD_DDCTBL_LBLTY_AM|NCH_PROFNL_CMPNT_CHRG_AMT|NCH_IP_NCVRD_CHRG_AMT|NCH_IP_TOT_DDCTN_AMT|CLM_TOT_PPS_CPTL_AMT|CLM_PPS_CPTL_FSP_AMT|CLM_PPS_CPTL_OUTLIER_AMT|CLM_PPS_CPTL_DSPRPRTNT_SHR_AMT|CLM_PPS_CPTL_IME_AMT|CLM_PPS_CPTL_EXCPTN_AMT|CLM_PPS_OLD_CPTL_HLD_HRMLS_AMT|CLM_PPS_CPTL_DRG_WT_NUM|CLM_UTLZTN_DAY_CNT|BENE_TOT_COINSRNC_DAYS_CNT|BENE_LRD_USED_CNT|CLM_NON_UTLZTN_DAYS_CNT|NCH_BLOOD_PNTS_FRNSHD_QTY|NCH_VRFD_NCVRD_STAY_FROM_DT|NCH_VRFD_NCVRD_STAY_THRU_DT|NCH_ACTV_OR_CVRD_LVL_CARE_THRU|NCH_BENE_MDCR_BNFTS_EXHTD_DT_I|NCH_BENE_DSCHRG_DT|CLM_DRG_CD|CLM_DRG_OUTLIER_STAY_CD|NCH_DRG_OUTLIER_APRVD_PMT_AMT|ADMTG_DGNS_CD|PRNCPAL_DGNS_CD|ICD_DGNS_CD1|CLM_POA_IND_SW1|ICD_DGNS_CD2|CLM_POA_IND_SW2|ICD_DGNS_CD3|CLM_POA_IND_SW3|ICD_DGNS_CD4|CLM_POA_IND_SW4|ICD_DGNS_CD5|CLM_POA_IND_SW5|ICD_DGNS_CD6|CLM_POA_IND_SW6|ICD_DGNS_CD7|CLM_POA_IND_SW7|ICD_DGNS_CD8|CLM_POA_IND_SW8|ICD_DGNS_CD9|CLM_POA_IND_SW9|ICD_DGNS_CD10|CLM_POA_IND_SW10|ICD_DGNS_CD11|CLM_POA_IND_SW11|ICD_DGNS_CD12|CLM_POA_IND_SW12|ICD_DGNS_CD13|CLM_POA_IND_SW13|ICD_DGNS_CD14|CLM_POA_IND_SW14|ICD_DGNS_CD15|CLM_POA_IND_SW15|ICD_DGNS_CD16|CLM_POA_IND_SW16|ICD_DGNS_CD17|CLM_POA_IND_SW17|ICD_DGNS_CD18|CLM_POA_IND_SW18|ICD_DGNS_CD19|CLM_POA_IND_SW19|ICD_DGNS_CD20|CLM_POA_IND_SW20|ICD_DGNS_CD21|CLM_POA_IND_SW21|ICD_DGNS_CD22|CLM_POA_IND_SW22|ICD_DGNS_CD23|CLM_POA_IND_SW23|ICD_DGNS_CD24|CLM_POA_IND_SW24|ICD_DGNS_CD25|CLM_POA_IND_SW25|FST_DGNS_E_CD|ICD_DGNS_E_CD1|CLM_E_POA_IND_SW1|ICD_DGNS_E_CD2|CLM_E_POA_IND_SW2|ICD_DGNS_E_CD3|CLM_E_POA_IND_SW3|ICD_DGNS_E_CD4|CLM_E_POA_IND_SW4|ICD_DGNS_E_CD5|CLM_E_POA_IND_SW5|ICD_DGNS_E_CD6|CLM_E_POA_IND_SW6|ICD_DGNS_E_CD7|CLM_E_POA_IND_SW7|ICD_DGNS_E_CD8|CLM_E_POA_IND_SW8|ICD_DGNS_E_CD9|CLM_E_POA_IND_SW9|ICD_DGNS_E_CD10|CLM_E_POA_IND_SW10|ICD_DGNS_E_CD11|CLM_E_POA_IND_SW11|ICD_DGNS_E_CD12|CLM_E_POA_IND_SW12|ICD_PRCDR_CD1|PRCDR_DT1|ICD_PRCDR_CD2|PRCDR_DT2|ICD_PRCDR_CD3|PRCDR_DT3|ICD_PRCDR_CD4|PRCDR_DT4|ICD_PRCDR_CD5|PRCDR_DT5|ICD_PRCDR_CD6|PRCDR_DT6|ICD_PRCDR_CD7|PRCDR_DT7|ICD_PRCDR_CD8|PRCDR_DT8|ICD_PRCDR_CD9|PRCDR_DT9|ICD_PRCDR_CD10|PRCDR_DT10|ICD_PRCDR_CD11|PRCDR_DT11|ICD_PRCDR_CD12|PRCDR_DT12|ICD_PRCDR_CD13|PRCDR_DT13|ICD_PRCDR_CD14|PRCDR_DT14|ICD_PRCDR_CD15|PRCDR_DT15|ICD_PRCDR_CD16|PRCDR_DT16|ICD_PRCDR_CD17|PRCDR_DT17|ICD_PRCDR_CD18|PRCDR_DT18|ICD_PRCDR_CD19|PRCDR_DT19|ICD_PRCDR_CD20|PRCDR_DT20|ICD_PRCDR_CD21|PRCDR_DT21|ICD_PRCDR_CD22|PRCDR_DT22|ICD_PRCDR_CD23|PRCDR_DT23|ICD_PRCDR_CD24|PRCDR_DT24|ICD_PRCDR_CD25|PRCDR_DT25|IME_OP_CLM_VAL_AMT|DSH_OP_CLM_VAL_AMT|CLM_UNCOMPD_CARE_PMT_AMT|CLM_LINE_NUM|REV_CNTR|HCPCS_CD|REV_CNTR_DDCTBL_COINSRNC_CD
0      -10000010254618|-10000930037831|V|60|25-Mar-20...
1      -10000010254653|-10000930038030|V|60|24-Sep-20...
2      -10000010254653|-10000930038031|V|60|09-May-20...
3      -10000010254656|-10000930038162|V|60|14-Jan-20...
4      -10000010254656|-10000930038162|V|60|14-Jan-20...
...                                                  ...
58061  -10000010288008|-10000931485965|V|60|08-Jan-20...
58062  -10000010288008|-10000931485967|V|60|23-Oct-20...
58063  -10000010288008|-10000931485969|V|60|22-Aug-20...
58064  -10000010288008|-10000931485971|V|60|13-Sep-20...
58065  -10000010288010|-10000931486024|V|60|11-Jun-20...

[58066 rows x 1 columns]

In [74]:
df = pd.read_csv('https://data.cms.gov/sites/default/files/2023-04/67157de9-d962-4af0-bf0e-3578b3afec58/inpatient.csv', sep = '|')

<ipython-input-74-d205db3038f8>:1: DtypeWarning: Columns (168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('https://data.cms.gov/sites/default/files/2023-04/67157de9-d962-4af0-bf0e-3578b3afec58/inpatient.csv', sep = '|')

In [75]:
df

,BENE_ID,CLM_ID,NCH_NEAR_LINE_REC_IDENT_CD,NCH_CLM_TYPE_CD,CLM_FROM_DT,CLM_THRU_DT,NCH_WKLY_PROC_DT,FI_CLM_PROC_DT,CLAIM_QUERY_CODE,PRVDR_NUM,...,PRCDR_DT24,ICD_PRCDR_CD25,PRCDR_DT25,IME_OP_CLM_VAL_AMT,DSH_OP_CLM_VAL_AMT,CLM_UNCOMPD_CARE_PMT_AMT,CLM_LINE_NUM,REV_CNTR,HCPCS_CD,REV_CNTR_DDCTBL_COINSRNC_CD
0,-10000010254618,-10000930037831,V,60,25-Mar-2015,25-Mar-2015,27-Mar-2015,NaN,3,011500,...,NaN,NaN,NaN,0,0,NaN,1,450,99221,NaN
1,-10000010254653,-10000930038030,V,60,24-Sep-2015,24-Sep-2015,25-Sep-2015,NaN,3,017129,...,NaN,NaN,NaN,0,0,NaN,1,450,99221,NaN
2,-10000010254653,-10000930038031,V,60,09-May-2017,10-May-2017,12-May-2017,NaN,3,010052,...,NaN,NaN,NaN,0,0,NaN,1,1,99024,3.0
3,-10000010254656,-10000930038162,V,60,14-Jan-2017,14-Jan-2017,20-Jan-2017,NaN,3,015455,...,NaN,NaN,NaN,0,0,NaN,1,450,73610,3.0
4,-10000010254656,-10000930038162,V,60,14-Jan-2017,14-Jan-2017,20-Jan-2017,NaN,3,015455,...,NaN,NaN,NaN,0,0,NaN,2,450,29515,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58061,-10000010288008,-10000931485965,V,60,08-Jan-2020,14-Jan-2020,17-Jan-2020,NaN,3,050243,...,NaN,NaN,NaN,0,0,NaN,1,1,99221,NaN
58062,-10000010288008,-10000931485967,V,60,23-Oct-2020,23-Oct-2020,30-Oct-2020,NaN,3,056428,...,NaN,NaN,NaN,0,0,NaN,1,450,99221,NaN
58063,-10000010288008,-10000931485969,V,60,22-Aug-2021,23-Aug-2021,27-Aug-2021,NaN,3,056428,...,NaN,NaN,NaN,0,0,NaN,1,450,99221,NaN
58064,-10000010288008,-10000931485971,V,60,13-Sep-2021,16-Sep-2021,17-Sep-2021,NaN,3,050243,...,NaN,NaN,NaN,0,0,NaN,1,1,99221,NaN
58065,-10000010288010,-10000931486024,V,60,11-Jun-2017,11-Jun-2017,16-Jun-2017,NaN,3,555851,...,NaN,NaN,NaN,0,0,NaN,1,450,99221,NaN

In [76]:
df.sample(25)

,BENE_ID,CLM_ID,NCH_NEAR_LINE_REC_IDENT_CD,NCH_CLM_TYPE_CD,CLM_FROM_DT,CLM_THRU_DT,NCH_WKLY_PROC_DT,FI_CLM_PROC_DT,CLAIM_QUERY_CODE,PRVDR_NUM,...,PRCDR_DT24,ICD_PRCDR_CD25,PRCDR_DT25,IME_OP_CLM_VAL_AMT,DSH_OP_CLM_VAL_AMT,CLM_UNCOMPD_CARE_PMT_AMT,CLM_LINE_NUM,REV_CNTR,HCPCS_CD,REV_CNTR_DDCTBL_COINSRNC_CD
4465,-10000010256736,-10000930124818,V,60,01-Dec-2016,01-Dec-2016,02-Dec-2016,NaN,3,065305,...,NaN,NaN,NaN,0,0,NaN,3,450,99401,3.0
33527,-10000010272989,-10000930851527,V,60,16-Aug-2019,07-Sep-2019,13-Sep-2019,NaN,3,34U133,...,NaN,NaN,NaN,0,0,NaN,14,1,L5701,3.0
30640,-10000010271353,-10000930774243,V,60,13-Feb-2018,13-Feb-2018,16-Feb-2018,NaN,3,331131,...,NaN,NaN,NaN,0,0,NaN,2,450,94640,3.0
4018,-10000010256636,-10000930118207,V,60,28-Sep-2021,28-Sep-2021,01-Oct-2021,NaN,3,060113,...,NaN,NaN,NaN,0,0,NaN,4,450,G0442,3.0
39236,-10000010275793,-10000930987752,V,60,15-Sep-2022,20-Sep-2022,23-Sep-2022,NaN,3,NaN,...,NaN,NaN,NaN,0,0,NaN,7,1,93229,2.0
14066,-10000010261685,-10000930350650,V,60,22-Mar-2021,22-Mar-2021,26-Mar-2021,NaN,3,145087,...,NaN,NaN,NaN,0,0,NaN,1,450,99221,NaN
601,-10000010255019,-10000930052784,V,60,05-Apr-2022,05-Apr-2022,08-Apr-2022,NaN,3,015133,...,NaN,NaN,NaN,0,0,NaN,3,450,M1069,3.0
18137,-10000010264105,-10000930460023,V,60,08-Jan-2023,09-Jan-2023,13-Jan-2023,NaN,3,183884,...,NaN,NaN,NaN,0,0,NaN,3,450,QS,3.0
37211,-10000010275183,-10000930956889,V,60,06-May-2019,06-May-2019,10-May-2019,NaN,3,375478,...,NaN,NaN,NaN,0,0,NaN,3,450,M1069,3.0
31392,-10000010271647,-10000930788248,V,60,16-Mar-2016,16-Mar-2016,18-Mar-2016,NaN,3,337438,...,NaN,NaN,NaN,0,0,NaN,8,450,99408,3.0
46930,-10000010280747,-10000931197610,V,60,04-Oct-2021,12-Oct-2021,15-Oct-2021,NaN,3,45T058,...,NaN,NaN,NaN,0,0,NaN,4,1,G0498,3.0
51536,-10000010282839,-10000931284144,V,60,03-Jun-2022,22-Jun-2022,24-Jun-2022,NaN,3,50T124,...,NaN,NaN,NaN,0,0,NaN,2,1,99024,3.0
52351,-10000010283457,-10000931309768,V,60,09-Jul-2022,10-Jul-2022,15-Jul-2022,NaN,3,515155,...,NaN,NaN,NaN,0,0,NaN,4,1,QS,3.0
3637,-10000010256461,-10000930111701,V,60,05-May-2019,05-May-2019,10-May-2019,NaN,3,065390,...,NaN,NaN,NaN,0,0,NaN,1,450,96156,2.0
33928,-10000010273270,-10000930865117,V,60,05-Aug-2018,05-Aug-2018,10-Aug-2018,NaN,3,345391,...,NaN,NaN,NaN,0,0,NaN,1,450,96156,3.0
17284,-10000010263376,-10000930432024,V,60,12-Dec-2021,12-Dec-2021,17-Dec-2021,NaN,3,165367,...,NaN,NaN,NaN,0,0,NaN,6,450,M1069,3.0
8108,-10000010258554,-10000930211723,V,60,03-Sep-2021,03-Sep-2021,10-Sep-2021,NaN,3,109449,...,NaN,NaN,NaN,0,0,NaN,3,450,96127,3.0
43925,-10000010278154,-10000931105992,V,60,09-Sep-2018,11-Sep-2018,14-Sep-2018,NaN,3,440082,...,NaN,NaN,NaN,0,0,NaN,3,1,L5701,3.0
32685,-10000010272503,-10000930824281,V,60,29-Mar-2015,29-Mar-2015,03-Apr-2015,NaN,3,335437,...,NaN,NaN,NaN,0,0,NaN,4,450,M1069,3.0
55625,-10000010286037,-10000931406766,V,60,02-Jul-2016,02-Jul-2016,08-Jul-2016,NaN,3,NaN,...,NaN,NaN,NaN,0,0,NaN,3,450,87999,2.0
28402,-10000010270379,-10000930728595,V,60,07-Nov-2019,20-Nov-2019,22-Nov-2019,NaN,3,324013,...,NaN,NaN,NaN,0,0,NaN,13,1,L5701,2.0
16909,-10000010263073,-10000930418480,V,60,20-Sep-2020,23-Sep-2020,25-Sep-2020,NaN,3,154064,...,NaN,NaN,NaN,0,0,NaN,5,1,L5701,3.0
16533,-10000010262794,-10000930404815,V,60,01-Aug-2019,01-Aug-2019,02-Aug-2019,NaN,3,155757,...,NaN,NaN,NaN,0,0,NaN,1,450,99221,NaN
36005,-10000010274378,-10000930917417,V,60,08-Aug-2019,11-Aug-2019,16-Aug-2019,NaN,3,360078,...,NaN,NaN,NaN,0,0,NaN,2,1,99024,3.0
35142,-10000010273853,-10000930895322,V,60,02-Mar-2017,02-Mar-2017,03-Mar-2017,NaN,3,361882,...,NaN,NaN,NaN,0,0,NaN,1,450,99221,NaN

In [77]:
### now lets look at column name
df.columns ##variable name we gave to the data set

Index(['BENE_ID', 'CLM_ID', 'NCH_NEAR_LINE_REC_IDENT_CD', 'NCH_CLM_TYPE_CD',
       'CLM_FROM_DT', 'CLM_THRU_DT', 'NCH_WKLY_PROC_DT', 'FI_CLM_PROC_DT',
       'CLAIM_QUERY_CODE', 'PRVDR_NUM',
       ...
       'PRCDR_DT24', 'ICD_PRCDR_CD25', 'PRCDR_DT25', 'IME_OP_CLM_VAL_AMT',
       'DSH_OP_CLM_VAL_AMT', 'CLM_UNCOMPD_CARE_PMT_AMT', 'CLM_LINE_NUM',
       'REV_CNTR', 'HCPCS_CD', 'REV_CNTR_DDCTBL_COINSRNC_CD'],
      dtype='object', length=197)

In [78]:
for column in df.columns:
    print(column) ####change the name, it could be x, column, just a place holder.

BENE_ID
CLM_ID
NCH_NEAR_LINE_REC_IDENT_CD
NCH_CLM_TYPE_CD
CLM_FROM_DT
CLM_THRU_DT
NCH_WKLY_PROC_DT
FI_CLM_PROC_DT
CLAIM_QUERY_CODE
PRVDR_NUM
CLM_FAC_TYPE_CD
CLM_SRVC_CLSFCTN_TYPE_CD
CLM_FREQ_CD
FI_NUM
CLM_MDCR_NON_PMT_RSN_CD
CLM_PMT_AMT
NCH_PRMRY_PYR_CLM_PD_AMT
NCH_PRMRY_PYR_CD
FI_CLM_ACTN_CD
PRVDR_STATE_CD
ORG_NPI_NUM
AT_PHYSN_UPIN
AT_PHYSN_NPI
OP_PHYSN_UPIN
OP_PHYSN_NPI
OT_PHYSN_UPIN
OT_PHYSN_NPI
CLM_MCO_PD_SW
PTNT_DSCHRG_STUS_CD
CLM_PPS_IND_CD
CLM_TOT_CHRG_AMT
CLM_ADMSN_DT
CLM_IP_ADMSN_TYPE_CD
CLM_SRC_IP_ADMSN_CD
NCH_PTNT_STATUS_IND_CD
CLM_PASS_THRU_PER_DIEM_AMT
NCH_BENE_IP_DDCTBL_AMT
NCH_BENE_PTA_COINSRNC_LBLTY_AM
NCH_BENE_BLOOD_DDCTBL_LBLTY_AM
NCH_PROFNL_CMPNT_CHRG_AMT
NCH_IP_NCVRD_CHRG_AMT
NCH_IP_TOT_DDCTN_AMT
CLM_TOT_PPS_CPTL_AMT
CLM_PPS_CPTL_FSP_AMT
CLM_PPS_CPTL_OUTLIER_AMT
CLM_PPS_CPTL_DSPRPRTNT_SHR_AMT
CLM_PPS_CPTL_IME_AMT
CLM_PPS_CPTL_EXCPTN_AMT
CLM_PPS_OLD_CPTL_HLD_HRMLS_AMT
CLM_PPS_CPTL_DRG_WT_NUM
CLM_UTLZTN_DAY_CNT
BENE_TOT_COINSRNC_DAYS_CNT
BENE_LRD_USED_CNT
CLM_NON_UTLZTN_DAYS_CNT
NCH_BLOOD_PNTS_FRNSHD_QTY
NCH_VRFD_NCVRD_STAY_FROM_DT
NCH_VRFD_NCVRD_STAY_THRU_DT
NCH_ACTV_OR_CVRD_LVL_CARE_THRU
NCH_BENE_MDCR_BNFTS_EXHTD_DT_I
NCH_BENE_DSCHRG_DT
CLM_DRG_CD
CLM_DRG_OUTLIER_STAY_CD
NCH_DRG_OUTLIER_APRVD_PMT_AMT
ADMTG_DGNS_CD
PRNCPAL_DGNS_CD
ICD_DGNS_CD1
CLM_POA_IND_SW1
ICD_DGNS_CD2
CLM_POA_IND_SW2
ICD_DGNS_CD3
CLM_POA_IND_SW3
ICD_DGNS_CD4
CLM_POA_IND_SW4
ICD_DGNS_CD5
CLM_POA_IND_SW5
ICD_DGNS_CD6
CLM_POA_IND_SW6
ICD_DGNS_CD7
CLM_POA_IND_SW7
ICD_DGNS_CD8
CLM_POA_IND_SW8
ICD_DGNS_CD9
CLM_POA_IND_SW9
ICD_DGNS_CD10
CLM_POA_IND_SW10
ICD_DGNS_CD11
CLM_POA_IND_SW11
ICD_DGNS_CD12
CLM_POA_IND_SW12
ICD_DGNS_CD13
CLM_POA_IND_SW13
ICD_DGNS_CD14
CLM_POA_IND_SW14
ICD_DGNS_CD15
CLM_POA_IND_SW15
ICD_DGNS_CD16
CLM_POA_IND_SW16
ICD_DGNS_CD17
CLM_POA_IND_SW17
ICD_DGNS_CD18
CLM_POA_IND_SW18
ICD_DGNS_CD19
CLM_POA_IND_SW19
ICD_DGNS_CD20
CLM_POA_IND_SW20
ICD_DGNS_CD21
CLM_POA_IND_SW21
ICD_DGNS_CD22
CLM_POA_IND_SW22
ICD_DGNS_CD23
CLM_POA_IND_SW23
ICD_DGNS_CD24
CLM_POA_IND_SW24
ICD_DGNS_CD25
CLM_POA_IND_SW25
FST_DGNS_E_CD
ICD_DGNS_E_CD1
CLM_E_POA_IND_SW1
ICD_DGNS_E_CD2
CLM_E_POA_IND_SW2
ICD_DGNS_E_CD3
CLM_E_POA_IND_SW3
ICD_DGNS_E_CD4
CLM_E_POA_IND_SW4
ICD_DGNS_E_CD5
CLM_E_POA_IND_SW5
ICD_DGNS_E_CD6
CLM_E_POA_IND_SW6
ICD_DGNS_E_CD7
CLM_E_POA_IND_SW7
ICD_DGNS_E_CD8
CLM_E_POA_IND_SW8
ICD_DGNS_E_CD9
CLM_E_POA_IND_SW9
ICD_DGNS_E_CD10
CLM_E_POA_IND_SW10
ICD_DGNS_E_CD11
CLM_E_POA_IND_SW11
ICD_DGNS_E_CD12
CLM_E_POA_IND_SW12
ICD_PRCDR_CD1
PRCDR_DT1
ICD_PRCDR_CD2
PRCDR_DT2
ICD_PRCDR_CD3
PRCDR_DT3
ICD_PRCDR_CD4
PRCDR_DT4
ICD_PRCDR_CD5
PRCDR_DT5
ICD_PRCDR_CD6
PRCDR_DT6
ICD_PRCDR_CD7
PRCDR_DT7
ICD_PRCDR_CD8
PRCDR_DT8
ICD_PRCDR_CD9
PRCDR_DT9
ICD_PRCDR_CD10
PRCDR_DT10
ICD_PRCDR_CD11
PRCDR_DT11
ICD_PRCDR_CD12
PRCDR_DT12
ICD_PRCDR_CD13
PRCDR_DT13
ICD_PRCDR_CD14
PRCDR_DT14
ICD_PRCDR_CD15
PRCDR_DT15
ICD_PRCDR_CD16
PRCDR_DT16
ICD_PRCDR_CD17
PRCDR_DT17
ICD_PRCDR_CD18
PRCDR_DT18
ICD_PRCDR_CD19
PRCDR_DT19
ICD_PRCDR_CD20
PRCDR_DT20
ICD_PRCDR_CD21
PRCDR_DT21
ICD_PRCDR_CD22
PRCDR_DT22
ICD_PRCDR_CD23
PRCDR_DT23
ICD_PRCDR_CD24
PRCDR_DT24
ICD_PRCDR_CD25
PRCDR_DT25
IME_OP_CLM_VAL_AMT
DSH_OP_CLM_VAL_AMT
CLM_UNCOMPD_CARE_PMT_AMT
CLM_LINE_NUM
REV_CNTR
HCPCS_CD
REV_CNTR_DDCTBL_COINSRNC_CD

In [79]:
# df.PRNCPAL_DGNS_CD
# df['PRNCPAL_DGNS_CD']

In [80]:
df['PRNCPAL_DGNS_CD']

0         S134XX
1          Z3480
2         T7432X
3         S8290X
4         S8290X
          ...
58061    T50901A
58062    T50901A
58063    T50901A
58064    T50901A
58065     S93409
Name: PRNCPAL_DGNS_CD, Length: 58066, dtype: object

In [81]:
#### get unique count of CLM_ID
count = df.CLM_ID.unique()
len(count) #unique names! This is not the unit of analysis or least common denominator?? important to understand what each row means

20867

In [82]:
df['PRNCPAL_DGNS_CD']. value_counts() ##most frequent/least frequent ICD 10 codes

PRNCPAL_DGNS_CD
Z733      11469
Z608       7216
T7432X     3314
Z604       3227
Z7682      3092
          ...
I25700        1
I200          1
E849          1
A4152         1
O00109        1
Name: count, Length: 190, dtype: int64

In [83]:
icd_primary_counts = df['PRNCPAL_DGNS_CD']. value_counts()

In [84]:
icd_primary_counts

PRNCPAL_DGNS_CD
Z733      11469
Z608       7216
T7432X     3314
Z604       3227
Z7682      3092
          ...
I25700        1
I200          1
E849          1
A4152         1
O00109        1
Name: count, Length: 190, dtype: int64

In [85]:
type(icd_primary_counts)

pandas.core.series.Series

In [86]:
type(df)

pandas.core.frame.DataFrame

In [87]:
df.dtypes ##dtypes tells us whether each column is an integer or a number, not ALWAYS accurate tho so be careful.

BENE_ID                          int64
CLM_ID                           int64
NCH_NEAR_LINE_REC_IDENT_CD      object
NCH_CLM_TYPE_CD                  int64
CLM_FROM_DT                     object
                                ...
CLM_UNCOMPD_CARE_PMT_AMT       float64
CLM_LINE_NUM                     int64
REV_CNTR                         int64
HCPCS_CD                        object
REV_CNTR_DDCTBL_COINSRNC_CD    float64
Length: 197, dtype: object

In [88]:
df['CLM_PMT_AMT'].describe()

count     58066.000000
mean      13638.307734
std       35993.907780
min          62.440000
25%         945.370000
50%        1481.715000
75%        9932.040000
max      598716.310000
Name: CLM_PMT_AMT, dtype: float64

In [89]:
print(df.head())

          BENE_ID          CLM_ID NCH_NEAR_LINE_REC_IDENT_CD  NCH_CLM_TYPE_CD  \
0 -10000010254618 -10000930037831                          V               60
1 -10000010254653 -10000930038030                          V               60
2 -10000010254653 -10000930038031                          V               60
3 -10000010254656 -10000930038162                          V               60
4 -10000010254656 -10000930038162                          V               60

   CLM_FROM_DT  CLM_THRU_DT NCH_WKLY_PROC_DT  FI_CLM_PROC_DT  \
0  25-Mar-2015  25-Mar-2015      27-Mar-2015             NaN
1  24-Sep-2015  24-Sep-2015      25-Sep-2015             NaN
2  09-May-2017  10-May-2017      12-May-2017             NaN
3  14-Jan-2017  14-Jan-2017      20-Jan-2017             NaN
4  14-Jan-2017  14-Jan-2017      20-Jan-2017             NaN

   CLAIM_QUERY_CODE PRVDR_NUM  ...  PRCDR_DT24  ICD_PRCDR_CD25  PRCDR_DT25  \
0                 3    011500  ...         NaN             NaN         NaN
1                 3    017129  ...         NaN             NaN         NaN
2                 3    010052  ...         NaN             NaN         NaN
3                 3    015455  ...         NaN             NaN         NaN
4                 3    015455  ...         NaN             NaN         NaN

   IME_OP_CLM_VAL_AMT DSH_OP_CLM_VAL_AMT  CLM_UNCOMPD_CARE_PMT_AMT  \
0                   0                  0                       NaN
1                   0                  0                       NaN
2                   0                  0                       NaN
3                   0                  0                       NaN
4                   0                  0                       NaN

   CLM_LINE_NUM REV_CNTR  HCPCS_CD  REV_CNTR_DDCTBL_COINSRNC_CD
0             1      450     99221                          NaN
1             1      450     99221                          NaN
2             1        1     99024                          3.0
3             1      450     73610                          3.0
4             2      450     29515                          3.0

[5 rows x 197 columns]

In [90]:
codex_columns = [
    'PRNCPAL_DGNS_CD',
    'ICD_DGNS_CD1',
    'ICD_PRCDR_CD1',
    'CLM_DRG_CD',
    'ADMTG_DGNS_CD',
    'HCPCS_CD',
    'FST_DGNS_E_CD',
    'NCH_DRG_OUTLIER_APRVD_PMT_AMT'
]
for column in codex_columns:
    print(f"Frequency counts for {column}:")
    value_counts = df[column].value_counts()
    print(df[column].value_counts())
    print("\n")

Frequency counts for PRNCPAL_DGNS_CD:
PRNCPAL_DGNS_CD
Z733      11469
Z608       7216
T7432X     3314
Z604       3227
Z7682      3092
          ...
I25700        1
I200          1
E849          1
A4152         1
O00109        1
Name: count, Length: 190, dtype: int64


Frequency counts for ICD_DGNS_CD1:
ICD_DGNS_CD1
Z733      13031
Z608       8227
T7432X     3727
Z604       3537
Z940       2858
          ...
T8611         1
E1141         1
E11610        1
I071          1
M069          1
Name: count, Length: 231, dtype: int64


Frequency counts for ICD_PRCDR_CD1:
ICD_PRCDR_CD1
GZ3        16142
Z741       12421
BW03ZZZ     3337
G4730       2134
F13         2054
           ...
3E03328        1
0HBU0ZX        1
02YA0Z2        1
0SRD0          1
0HCV3ZZ        1
Name: count, Length: 114, dtype: int64


Frequency counts for CLM_DRG_CD:
CLM_DRG_CD
951.0    28831
950.0     1456
949.0     1332
922.0     1110
923.0     1015
         ...
814.0        1
918.0        1
870.0        1
812.0        1
656.0        1
Name: count, Length: 167, dtype: int64


Frequency counts for ADMTG_DGNS_CD:
ADMTG_DGNS_CD
Z7682      2881
T50901A    2541
Z951       1694
Z95818     1058
C3490       940
           ...
E849          1
A4152         1
O00109        1
I200          1
C9200         1
Name: count, Length: 65, dtype: int64


Frequency counts for HCPCS_CD:
HCPCS_CD
99221    8298
G0444    7990
96156    5080
99408    4196
99495    3867
         ...
S9361       1
S9355       1
S9374       1
S9377       1
G9829       1
Name: count, Length: 106, dtype: int64


Frequency counts for FST_DGNS_E_CD:
FST_DGNS_E_CD
W86    10445
X58     7202
W19     4899
Y92     3291
Y83     2488
       ...
V28        1
V78        1
X93        1
X80        1
X72        1
Name: count, Length: 137, dtype: int64


Frequency counts for NCH_DRG_OUTLIER_APRVD_PMT_AMT:
NCH_DRG_OUTLIER_APRVD_PMT_AMT
0    58066
Name: count, dtype: int64

In [92]:
codex_columns = [
    'PRNCPAL_DGNS_CD',
    'ICD_DGNS_CD1',
    'ICD_PRCDR_CD1',
    'CLM_DRG_CD',
    'ADMTG_DGNS_CD',
    'HCPCS_CD',
    'FST_DGNS_E_CD',
    'NCH_DRG_OUTLIER_APRVD_PMT_AMT'
]
for column in codex_columns:
    print(f"Missing counts for {column}:")
    value_counts = df[column].value_counts()
    print(df[column].value_counts())
    print("\n")

Missing counts for PRNCPAL_DGNS_CD:
PRNCPAL_DGNS_CD
Z733      11469
Z608       7216
T7432X     3314
Z604       3227
Z7682      3092
          ...
I25700        1
I200          1
E849          1
A4152         1
O00109        1
Name: count, Length: 190, dtype: int64


Missing counts for ICD_DGNS_CD1:
ICD_DGNS_CD1
Z733      13031
Z608       8227
T7432X     3727
Z604       3537
Z940       2858
          ...
T8611         1
E1141         1
E11610        1
I071          1
M069          1
Name: count, Length: 231, dtype: int64


Missing counts for ICD_PRCDR_CD1:
ICD_PRCDR_CD1
GZ3        16142
Z741       12421
BW03ZZZ     3337
G4730       2134
F13         2054
           ...
3E03328        1
0HBU0ZX        1
02YA0Z2        1
0SRD0          1
0HCV3ZZ        1
Name: count, Length: 114, dtype: int64


Missing counts for CLM_DRG_CD:
CLM_DRG_CD
951.0    28831
950.0     1456
949.0     1332
922.0     1110
923.0     1015
         ...
814.0        1
918.0        1
870.0        1
812.0        1
656.0        1
Name: count, Length: 167, dtype: int64


Missing counts for ADMTG_DGNS_CD:
ADMTG_DGNS_CD
Z7682      2881
T50901A    2541
Z951       1694
Z95818     1058
C3490       940
           ...
E849          1
A4152         1
O00109        1
I200          1
C9200         1
Name: count, Length: 65, dtype: int64


Missing counts for HCPCS_CD:
HCPCS_CD
99221    8298
G0444    7990
96156    5080
99408    4196
99495    3867
         ...
S9361       1
S9355       1
S9374       1
S9377       1
G9829       1
Name: count, Length: 106, dtype: int64


Missing counts for FST_DGNS_E_CD:
FST_DGNS_E_CD
W86    10445
X58     7202
W19     4899
Y92     3291
Y83     2488
       ...
V28        1
V78        1
X93        1
X80        1
X72        1
Name: count, Length: 137, dtype: int64


Missing counts for NCH_DRG_OUTLIER_APRVD_PMT_AMT:
NCH_DRG_OUTLIER_APRVD_PMT_AMT
0    58066
Name: count, dtype: int64

In [93]:
##STEP 2: Explore the Dataset
icd_codes = df['ICD_DGNS_CD1']
drg_codes = df['PRNCPAL_DGNS_CD']
hcpcs_codes = df['HCPCS_CD']

In [95]:
codex_columns = [
    'PRNCPAL_DGNS_CD',
    'ICD_DGNS_CD1',
    'ICD_PRCDR_CD1',
    'CLM_DRG_CD',
    'ADMTG_DGNS_CD',
    'HCPCS_CD',
    'FST_DGNS_E_CD',
    'NCH_DRG_OUTLIER_APRVD_PMT_AMT'
]
for column in codex_columns:
    print(f"Frequency counts for {column}:")
    value_counts = df[column].value_counts()
    print(df[column].value_counts())
    print("\n")

Frequency counts for PRNCPAL_DGNS_CD:
PRNCPAL_DGNS_CD
Z733      11469
Z608       7216
T7432X     3314
Z604       3227
Z7682      3092
          ...
I25700        1
I200          1
E849          1
A4152         1
O00109        1
Name: count, Length: 190, dtype: int64


Frequency counts for ICD_DGNS_CD1:
ICD_DGNS_CD1
Z733      13031
Z608       8227
T7432X     3727
Z604       3537
Z940       2858
          ...
T8611         1
E1141         1
E11610        1
I071          1
M069          1
Name: count, Length: 231, dtype: int64


Frequency counts for ICD_PRCDR_CD1:
ICD_PRCDR_CD1
GZ3        16142
Z741       12421
BW03ZZZ     3337
G4730       2134
F13         2054
           ...
3E03328        1
0HBU0ZX        1
02YA0Z2        1
0SRD0          1
0HCV3ZZ        1
Name: count, Length: 114, dtype: int64


Frequency counts for CLM_DRG_CD:
CLM_DRG_CD
951.0    28831
950.0     1456
949.0     1332
922.0     1110
923.0     1015
         ...
814.0        1
918.0        1
870.0        1
812.0        1
656.0        1
Name: count, Length: 167, dtype: int64


Frequency counts for ADMTG_DGNS_CD:
ADMTG_DGNS_CD
Z7682      2881
T50901A    2541
Z951       1694
Z95818     1058
C3490       940
           ...
E849          1
A4152         1
O00109        1
I200          1
C9200         1
Name: count, Length: 65, dtype: int64


Frequency counts for HCPCS_CD:
HCPCS_CD
99221    8298
G0444    7990
96156    5080
99408    4196
99495    3867
         ...
S9361       1
S9355       1
S9374       1
S9377       1
G9829       1
Name: count, Length: 106, dtype: int64


Frequency counts for FST_DGNS_E_CD:
FST_DGNS_E_CD
W86    10445
X58     7202
W19     4899
Y92     3291
Y83     2488
       ...
V28        1
V78        1
X93        1
X80        1
X72        1
Name: count, Length: 137, dtype: int64


Frequency counts for NCH_DRG_OUTLIER_APRVD_PMT_AMT:
NCH_DRG_OUTLIER_APRVD_PMT_AMT
0    58066
Name: count, dtype: int64

In [96]:
##STEP 3: Analyze the Frequency of Each Unique Value
icd_frequency = icd_codes.value_counts()
drg_frequency = drg_codes.value_counts()
hcpcs_frequency = hcpcs_codes.value_counts()

In [97]:
print("ICD Codes Frequency:\n", icd_frequency)
print("DRG Codes Frequency:\n", drg_frequency)
print("HCPCS Codes Frequency:\n", hcpcs_frequency)

ICD Codes Frequency:
 ICD_DGNS_CD1
Z733      13031
Z608       8227
T7432X     3727
Z604       3537
Z940       2858
          ...
T8611         1
E1141         1
E11610        1
I071          1
M069          1
Name: count, Length: 231, dtype: int64
DRG Codes Frequency:
 PRNCPAL_DGNS_CD
Z733      11469
Z608       7216
T7432X     3314
Z604       3227
Z7682      3092
          ...
I25700        1
I200          1
E849          1
A4152         1
O00109        1
Name: count, Length: 190, dtype: int64
HCPCS Codes Frequency:
 HCPCS_CD
99221    8298
G0444    7990
96156    5080
99408    4196
99495    3867
         ...
S9361       1
S9355       1
S9374       1
S9377       1
G9829       1
Name: count, Length: 106, dtype: int64

In [98]:
codex_columns = [
    'PRNCPAL_DGNS_CD',
    'ICD_DGNS_CD1',
    'ICD_PRCDR_CD1',
    'CLM_DRG_CD',
    'ADMTG_DGNS_CD',
    'HCPCS_CD',
    'FST_DGNS_E_CD',
    'NCH_DRG_OUTLIER_APRVD_PMT_AMT'
]
for column in codex_columns:
    print(f"Missing counts for {column}:")
    value_counts = df[column].value_counts()
    print(df[column].value_counts())
    print("\n")

Missing counts for PRNCPAL_DGNS_CD:
PRNCPAL_DGNS_CD
Z733      11469
Z608       7216
T7432X     3314
Z604       3227
Z7682      3092
          ...
I25700        1
I200          1
E849          1
A4152         1
O00109        1
Name: count, Length: 190, dtype: int64


Missing counts for ICD_DGNS_CD1:
ICD_DGNS_CD1
Z733      13031
Z608       8227
T7432X     3727
Z604       3537
Z940       2858
          ...
T8611         1
E1141         1
E11610        1
I071          1
M069          1
Name: count, Length: 231, dtype: int64


Missing counts for ICD_PRCDR_CD1:
ICD_PRCDR_CD1
GZ3        16142
Z741       12421
BW03ZZZ     3337
G4730       2134
F13         2054
           ...
3E03328        1
0HBU0ZX        1
02YA0Z2        1
0SRD0          1
0HCV3ZZ        1
Name: count, Length: 114, dtype: int64


Missing counts for CLM_DRG_CD:
CLM_DRG_CD
951.0    28831
950.0     1456
949.0     1332
922.0     1110
923.0     1015
         ...
814.0        1
918.0        1
870.0        1
812.0        1
656.0        1
Name: count, Length: 167, dtype: int64


Missing counts for ADMTG_DGNS_CD:
ADMTG_DGNS_CD
Z7682      2881
T50901A    2541
Z951       1694
Z95818     1058
C3490       940
           ...
E849          1
A4152         1
O00109        1
I200          1
C9200         1
Name: count, Length: 65, dtype: int64


Missing counts for HCPCS_CD:
HCPCS_CD
99221    8298
G0444    7990
96156    5080
99408    4196
99495    3867
         ...
S9361       1
S9355       1
S9374       1
S9377       1
G9829       1
Name: count, Length: 106, dtype: int64


Missing counts for FST_DGNS_E_CD:
FST_DGNS_E_CD
W86    10445
X58     7202
W19     4899
Y92     3291
Y83     2488
       ...
V28        1
V78        1
X93        1
X80        1
X72        1
Name: count, Length: 137, dtype: int64


Missing counts for NCH_DRG_OUTLIER_APRVD_PMT_AMT:
NCH_DRG_OUTLIER_APRVD_PMT_AMT
0    58066
Name: count, dtype: int64

In [99]:
## STEP 4: HANDLING MISSING DATA
missing_icd = icd_codes.isnull().sum()
missing_drg = drg_codes.isnull().sum()
missing_hcpcs = hcpcs_codes.isnull().sum()

In [100]:
print(f"Missing ICD Codes: {missing_icd}")
print(f"Missing DRG Codes: {missing_drg}")
print(f"Missing HCPCS Codes: {missing_hcpcs}")

Missing ICD Codes: 0
Missing DRG Codes: 0
Missing HCPCS Codes: 0

In [101]:
df['ICD_DGNS_CD1'].fillna('MISSING', inplace=True)
df['PRNCPAL_DGNS_CD'].fillna('MISSING', inplace=True)
df['HCPCS_CD'].fillna('MISSING', inplace=True)

In [102]:
## STEP 5: Summary of Findings
print("Top 5 Most Common ICD Codes:\n", icd_frequency.head())
print("Top 5 Most Common DRG Codes:\n", drg_frequency.head())
print("Top 5 Most Common HCPCS Codes:\n", hcpcs_frequency.head())

Top 5 Most Common ICD Codes:
 ICD_DGNS_CD1
Z733      13031
Z608       8227
T7432X     3727
Z604       3537
Z940       2858
Name: count, dtype: int64
Top 5 Most Common DRG Codes:
 PRNCPAL_DGNS_CD
Z733      11469
Z608       7216
T7432X     3314
Z604       3227
Z7682      3092
Name: count, dtype: int64
Top 5 Most Common HCPCS Codes:
 HCPCS_CD
99221    8298
G0444    7990
96156    5080
99408    4196
99495    3867
Name: count, dtype: int64

In [103]:
##Additional Analysis Example
diabetes_related = df[df['ICD_DGNS_CD1'].str.contains('E11', na=False)]
common_drg_for_diabetes = diabetes_related['PRNCPAL_DGNS_CD'].value_counts()
print("Most Common DRG Codes for Patients with ICD Code E11 (Type 2 Diabetes):\n", common_drg_for_diabetes)

Most Common DRG Codes for Patients with ICD Code E11 (Type 2 Diabetes):
 PRNCPAL_DGNS_CD
E1122      54
T50901A    15
E113519     6
E119        6
I0981       3
I509        2
J45909      2
E113299     2
Z3480       1
M797        1
Name: count, dtype: int64